name = "dev-utils-online"
compatibility_date = "2024-08-29"

[build]
command = "npm run build"

[site]
bucket = ".next/static"

[build.upload]
format = "service-worker"

[env.production]
pages_build_output_dir = ".next"